deploy:
  provider: heroku
  api_key:
    secure: XGMM3F0d7MxevdizOacBEsnGyOTV3o8mKCNQLif5L22E0R8xrEacZG6hzqIvZVsHKbHiIARSSnLEZ97kqxnrZPsY1S0D0LdELukmh9J4eZVENp+Xn39PpwJgmelezNe5hJ3JiRl6oi1L2Alr9sqpfVbEUV5AXuPrPpCJhVWp8V79nQ/YfU/Sk3/qasBo0c7+qDARBuq6tw6zROl6TdLmHKJXiKRNHTT1EhXNQKagD93tkIbPIxXlNKDqgp5oHWKxWOGBNgAyL1LmE7in3I0D6H/qD5jr4+LddlQKut8U1qjPqUxMbwTRkjmmlxEsNo/WtWurMY+E2hWDX+q0caI47l80dQw9qQc2dNwlTw2C70V+koJejzMsz9OsjPd4uErnU8MQsZX5hcqpFIsr+ziNtrO2iakMm3BtgDEyXdQ82FrIZrVdjBqngCihbk1uTeGDLlCrWgYXbkzBS56voREy7ZpIB4T/s1NQ3i15+LDVhikrDYlrYaXTFhT8AT7hMUgLwu28nPNEf6zvZDfRY/0jJBBlCDENrMQjhFH8B722SRRlseLIZyGw7U4wH6tflMSlXU2HIyHvJnVYaMbC9F6l+wQjkvFE/upb5I7kCKGfqYqB60qCWhc81snBd0+EGcl5087ATHCgMswAhic55FPyJuXd8lZJJUFbD1A1C290H1o=
  app: baddie-match
  run:
  - cd front-end
  - npm run build
